### ISSUE TITLE
Current .gitignore does not cover enough common files

### ISSUE THREAD

**Issue by Astrea49** [Firefly042/ultimate-assistant-pycord#28]
## Is your feature request related to a problem? Please describe
The current `.gitignore` manages to leave out a *lot* of Python files that can be auto created and used, but also aren't necessarily great to have in a public repo.

Among things left out are:
- `venvs`
- Some instances of `__pycache__`

## Describe the solution you'd like
A better `.gitignore` that includes these things.

## Describe alternatives you've considered
Specifying my IDE not to commit those files, but it gets annoying after a while 😅.

**Comment by Firefly042** [comment]
I simply do not include the virtual env in the same directory as the bot, and I would assume that someone who is sincerely working with the code would either edit the .gitignore to ignore their venv directory or use a similar practice. Ignoring pycache would be a good idea based on #26 though. Admittedly, I just removed them because they were an eyesore and the bot should not be restarting often at all. But you're correct there.

**Comment by Firefly042** [comment]
Addressed in #17
