### ISSUE TITLE
Use connection pooling (on postgresql branch)

### ISSUE THREAD

**Issue by Firefly042** [Firefly042/ultimate-assistant-pycord#47]
## Current code (or state of code)
The DB connection currently uses a single asynchronous connection. Occasionally, this means that a user will be blocked from using the connection, causing their command to not respond.

## Proposed revision(s)
Use a reasonably sized connection pool and adjust each class method accordingly

## Additional context
Developer is inexperienced with this.

**Comment by Astrea49** [comment]
This is my calling. /lh

You can easily get away with just changing line 39 in `db.py` to use `pg.create_pool` instead of `pg.connect` - the defaults for pool creation are pretty sane (honestly, you shouldn't feel the need to specify the size except in weird scenarios), and it'll automatically handle creating pools and all for each statement run.

Admittedly, though, acquiring a pool per function in `db.py` rather than letting `asyncpg` acquire a pool each time a statement is run (what it does in the background if you do `conn.execute` or the like) would be more efficient. Maybe not by too much, but still.

**Comment by Firefly042** [comment]
Gave it a shot in #48. If I'm correct, it should be acquiring from the pool on each function call. The issue very seldom arises from what I can see, but it's better to be safe than sorry.
